### ISSUE TITLE
Setup vanity import path

### ISSUE THREAD

**Issue by sebastianst** [perun-network/poly-go#1]
As we did for `perun.network/go-perun`, create the vanity import path meta info html files for this module `polycry.pt/poly-go` using [vangen](https://github.com/leighmcculloch/vangen), see also [this blog post](https://sagikazarmark.hu/blog/vanity-import-paths-in-go/).

Ideally, we create a common vanity import path generator repo for all our go projects that use vanity import paths, like [this one](https://github.com/emperror/vanity-imports) mentioned in the blog post above.

**Comment by ggwpez** [comment]
Works.
